### ISSUE TITLE
add post toggle actions to allow for things like alerts

### ISSUE THREAD

**Issue by amyoulton** [steamclock/debug-menu-ios#21]
In Ridwell, we're using toggles within our debug menu that require us to force restart our app.

Right now, `DebugToggleAction` takes a `Binding<Bool>` that is set when the toggle is interacted with. Attaching something like a "force restart app" alert within the toggle's set means the alert pops up before the toggle UI is swapped. Here is a video detailing this example:

https://user-images.githubusercontent.com/62073522/234391775-54eca8a7-1f06-4ed7-ac15-b40f224bf4f2.MP4

Instead, it would be great to add in an optional `toggleAction` that we can listen for with an `onChange` attached to the toggle in the UI, so the popup would come after the toggle.

I debated whether this seemed like an edge case only relevant to this situation, but I think there may be a decent amount of use cases where we may want to complete a secondary action after the toggle animation is finished.

## Update
It seems adding any action inside of the bindings set actually prevents the toggle from completing for some reason:

```
 let testBlockingUserAlert = DebugToggleAction(
            title: $toggleBlockingAlert.displayTitle,
            toggle: Binding(
                get: {
                    self.toggleBlockingAlert
                },
                set: {
                    self.toggleBlockingAlert = $0
                    self.toggleNonBlockingAlert = false
                    Defaults[\.testMobileAlert] = $0 ? .blocking : nil
                    AlertController.shared.showToast(message: "Push notification sent", type: .success)
                }
            )
        )
```

https://user-images.githubusercontent.com/62073522/234394532-a3d5a46f-ab2e-43f9-bedc-5d732c7c5984.MP4

**Comment by AZielinsky95** [comment]
Closing as was done in https://github.com/steamclock/debug-menu-ios/commit/674720c1763614ab8461480405f0f698441f8766
