### ISSUE TITLE
Fix concurrency issue in DebugSections

### ISSUE THREAD

**Issue by amyoulton** [steamclock/debug-menu-ios#24]
![279752844-56bbc586-18a8-46f3-bab4-eaceb8aa8f2d](https://github.com/steamclock/debug-menu-ios/assets/62073522/469791a2-6828-4dce-ab25-29943b4b9b19)

The debug sections need to be running on the main thread, since they are updating the UI. We're experiencing the effects of this in Ridwell atm where the sections are not updating on change.

**Comment by AZielinsky95** [comment]
This issue is due to mutating the sections property on a background thread in the client code, not with the library.
